### ISSUE TITLE
The code is not excutable

### ISSUE THREAD

**Issue by Snnzhao** [WHUIR/KOPRA#2]
I am very interested in this work. But the code provided is not excutable. The preprocessing part is missing and 
a lot of parameters is blank.
Looking forward to excutable code if possilbe.

**Comment by Braylon1002** [comment]
The parameter setting is shown in the paper. And the preprocessing part is implemented with dgl library. The code is executable if your inputs are dgl graphs. The original dgl graphs are so big, you can generate graphs according to the paper.
